### ISSUE TITLE
Message for Lothy 

### ISSUE THREAD

**Issue by Rodgerwilco** [Lothy/OpenClassic#1]
I can't login on the new forum but I saw this post.
https://forum.moparisthebest.com/t/aposbot-com-down/555841/8

I do own https://www.reddit.com/r/RSCDev/ and r/RS2Dev if needed. 
If you can post on that thread and let Jorgen and Cleako know that'd be great :)

**Comment by Marwolf** [comment]
Is Cleako. Doth now know.

**Comment by Lothy** [comment]
Yeah, knew you were Cleako. :)
